kind = "api"
previewPath = "/api"
title = "Flask API"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "Flask API"
paths = ["/api"]

[services.development]
run = "bash -c 'cd /home/runner/workspace/artifacts/flask-api && python app.py'"

[services.production]

[services.production.build]
args = ["pip", "install", "-r", "/home/runner/workspace/artifacts/flask-api/requirements.txt"]

[services.production.run]
args = ["bash", "-c", "cd /home/runner/workspace/artifacts/flask-api && gunicorn -w 4 --timeout 600 --graceful-timeout 30 -b 0.0.0.0:8080 'app:create_app()'"]

[services.production.health.startup]
path = "/api/healthz"
