kind = "api"
previewPath = "/api"
title = "Flask API"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "Flask API"
paths = ["/api"]

[services.development]
run = "python artifacts/flask-api/app.py"

[services.production]

[services.production.build]
args = ["pip", "install", "-r", "artifacts/flask-api/requirements.txt"]

[services.production.run]
args = ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "app:create_app()"]

[services.production.health.startup]
path = "/api/healthz"
